//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartı
    {
        public int StokKod { get; set; }
        public string StokKart { get; set; }
    
        public virtual StokHareket StokHareket { get; set; }
    }
}
