//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokUygulaması
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokHareket
    {
        public int Id { get; set; }
        public Nullable<int> Girdi { get; set; }
        public Nullable<int> Cıktı { get; set; }
    
        public virtual StokKartı StokKartı { get; set; }
    }
}
